Write-Verbose "Loading Adaptive Card type collections..."

[Diagnostics.CodeAnalysis.SuppressMessageAttribute('PSUseDeclaredVarsMoreThanAssignments', '', Justification = 'collection variables are used in validation scripts')]
$script:_AdaptiveCardAllowedActionTypes = @(
    "Action.Execute",
    "Action.InsertImage",
    "Action.OpenUrl",
    "Action.OpenUrlDialog",
    "Action.Popover",
    "Action.ResetInputs",
    "Action.ShowCard",
    "Action.Submit",
    "Action.ToggleVisibility"
)

[Diagnostics.CodeAnalysis.SuppressMessageAttribute('PSUseDeclaredVarsMoreThanAssignments', '', Justification = 'collection variables are used in validation scripts')]
$script:_AdaptiveCardAllowedElementTypes = @(
    "ActionSet",
    "Badge",
    "Carousel",
    "Chart.Donut",
    "Chart.Gauge",
    "Chart.HorizontalBar",
    "Chart.HorizontalBar.Stacked",
    "Chart.Line",
    "Chart.Pie",
    "Chart.VerticalBar",
    "Chart.VerticalBar.Grouped",
    "CodeBlock",
    "ColumnSet",
    "Component.graph.microsoft.com/event",
    "Component.graph.microsoft.com/file",
    "Component.graph.microsoft.com/resource",
    "Component.graph.microsoft.com/user",
    "Component.graph.microsoft.com/users",
    "CompoundButton",
    "Container",
    "FactSet",
    "Icon",
    "Image",
    "ImageSet",
    "Input.ChoiceSet",
    "Input.Date",
    "Input.Number",
    "Input.Rating",
    "Input.Text",
    "Input.Time",
    "Input.Toggle",
    "Media",
    "ProgressBar",
    "ProgressRing",
    "Rating",
    "RichTextBlock",
    "Table",
    "TextBlock"
)

[Diagnostics.CodeAnalysis.SuppressMessageAttribute('PSUseDeclaredVarsMoreThanAssignments', '', Justification = 'collection variables are used in validation scripts')]
$script:_AdaptiveCardAllowedFallbackElementTypes = @(
    "Container",
    "ActionSet",
    "ColumnSet",
    "Media",
    "RichTextBlock",
    "Table",
    "TextBlock",
    "FactSet",
    "ImageSet",
    "Image",
    "Input.Text",
    "Input.Date",
    "Input.Time",
    "Input.Number",
    "Input.Toggle",
    "Input.ChoiceSet",
    "Input.Rating",
    "Rating",
    "CompoundButton",
    "Icon",
    "Carousel",
    "Badge",
    "ProgressRing",
    "ProgressBar",
    "Chart.Donut",
    "Chart.Pie",
    "Chart.VerticalBar.Grouped",
    "Chart.VerticalBar",
    "Chart.HorizontalBar",
    "Chart.HorizontalBar.Stacked",
    "Chart.Line",
    "Chart.Gauge",
    "CodeBlock",
    "Component.graph.microsoft.com/user",
    "Component.graph.microsoft.com/users",
    "Component.graph.microsoft.com/resource",
    "Component.graph.microsoft.com/file",
    "Component.graph.microsoft.com/event"
)