#
# Module manifest for module 'MvRAdaptiveCards'
#
# Generated by: Michael van Rooijen
#
# Generated on: 3-11-2025
#

@{

# Script module or binary module file associated with this manifest.
RootModule = 'MvRAdaptiveCards.psm1'

# Version number of this module.
ModuleVersion = '0.8.6'

# Supported PSEditions
CompatiblePSEditions = 'Desktop', 'Core'

# ID used to uniquely identify this module
GUID = '55db3db7-b8a1-4d0e-ade3-b10d047518ef'

# Author of this module
Author = 'Michael van Rooijen'

# Company or vendor of this module
CompanyName = 'Personal development project'

# Copyright statement for this module
Copyright = '(c) Michael van Rooijen. All rights reserved.'

# Description of the functionality provided by this module
Description = 'This module provides functions for working with Adaptive Cards in PowerShell in a similar fashion as the popular module PSWriteHTML does for HTML generation. Please read the documentation on GitHub for more information. (https://github.com/Michael19842/PowerShell.MvRAdaptiveCards.Module)'

# Minimum version of the PowerShell engine required by this module
PowerShellVersion = '5.1'

# Name of the PowerShell host required by this module
# PowerShellHostName = ''

# Minimum version of the PowerShell host required by this module
# PowerShellHostVersion = ''

# Minimum version of Microsoft .NET Framework required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
# DotNetFrameworkVersion = ''

# Minimum version of the common language runtime (CLR) required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
# ClrVersion = ''

# Processor architecture (None, X86, Amd64) required by this module
# ProcessorArchitecture = ''

# Modules that must be imported into the global environment prior to importing this module
# RequiredModules = @()

# Assemblies that must be loaded prior to importing this module
# RequiredAssemblies = @()

# Script files (.ps1) that are run in the caller's environment prior to importing this module.
# ScriptsToProcess = @()

# Type files (.ps1xml) to be loaded when importing this module
# TypesToProcess = @()

# Format files (.ps1xml) to be loaded when importing this module
# FormatsToProcess = @()

# Modules to import as nested modules of the module specified in RootModule/ModuleToProcess
# NestedModules = @()

# Functions to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no functions to export.
FunctionsToExport = 'Build-CardFromTemplate', 'Find-CardTemplateTag', 'Get-CardResponse',
	           'New-AdaptiveCard', 'New-CardActionOpenUrl', 'New-CardActionSet',
	           'New-CardActionShowCard', 'New-CardActionSubmit',
	           'New-CardActionToggleVisibility', 'New-CardBadge', 'New-CardCarousel',
	           'New-CardCarouselPage', 'New-CardChartDonut', 'New-CardChartGauge',
	           'New-CardCodeBlock', 'New-CardColumn', 'New-CardColumnSet',
	           'New-CardCompoundButton', 'New-CardContainer', 'New-CardFactSet',
	           'New-CardGridArea', 'New-CardIcon', 'New-CardImage', 'New-CardImageSet',
	           'New-CardInputChoiceSet', 'New-CardInputDate', 'New-CardInputNumber',
	           'New-CardInputRating', 'New-CardInputText', 'New-CardInputTime',
	           'New-CardInputToggle', 'New-CardLayoutAreaGrid', 'New-CardLayoutFlow',
	           'New-CardLayoutStack', 'New-CardMedia', 'New-CardMediaCaptionSource',
	           'New-CardProgressBar', 'New-CardRichTextblock', 'New-CardTable',
	           'New-CardTemplateTag', 'New-CardTextBlock', 'Out-CardPreview',
	           'Out-OnlineDesigner', 'Send-CardViaClassicOutlook',
	           'Send-CardViaSMTP', 'Send-CardViaTeams', 'Set-CardDefaultFallback',
	           'Set-CardDefaultResponseSetting', 'Set-CardDefaultSmtpSetting',
	           'Set-CardDefaultTeamsSetting'

# Cmdlets to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no cmdlets to export.
CmdletsToExport = @()

# Variables to export from this module
VariablesToExport = '*'

# Aliases to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no aliases to export.
AliasesToExport = @()

# DSC resources to export from this module
# DscResourcesToExport = @()

# List of all modules packaged with this module
# ModuleList = @()

# List of all files packaged with this module
FileList = 'MvRAdaptiveCards.psd1', 'MvRAdaptiveCards.psm1',
	           'ArgumentCompleters/New-AdaptiveCard.ps1',
	           'ArgumentCompleters/New-CardBadge.ps1',
	           'ArgumentCompleters/New-CardIcon.ps1',
	           'Collection/AdaptiveCardIcon.ps1',
	           'Collection/AdaptiveCardStyle.ps1',
	           'Private/Element/New-CardTextRun.ps1',
	           'Private/Helper/Build-ExtensionsPayload.ps1',
	           'Private/Helper/Convert-ObjectToHashtable.ps1',
	           'Private/Helper/ConvertFrom-JsonAsHashtable.ps1',
	           'Private/Helper/Find-AvailablePort.ps1', 'Private/Helper/IIF.ps1',
	           'Private/Helper/New-LocalCardWebserver.ps1',
	           'Private/Helper/Write-Banner.ps1',
	           'Private/Helper/Write-ColoredHost.ps1',
	           'Private/Schema/Test-CardSchema.ps1',
	           'Private/SettingsFile/DefaultSettings.json',
	           'Private/SettingsFile/Get-CardSetting.ps1',
	           'Private/SettingsFile/Set-CardSetting.ps1',
	           'Public/New-AdaptiveCard.ps1',
	           'Public/Application/Get-CardResponse.ps1',
	           'Public/Application/Out-CardPreview.ps1',
	           'Public/Application/Out-OnlineDesigner.ps1',
	           'Public/Application/Send-CardViaClassicOutlook.ps1',
	           'Public/Application/Send-CardViaSMTP.ps1',
	           'Public/Application/Send-CardViaTeams.ps1',
	           'Public/Application/Set-CardDefaultFallback.ps1',
	           'Public/Application/Set-CardDefaultResponseSetting.ps1',
	           'Public/Application/Set-CardDefaultSmtpSetting.ps1',
	           'Public/Application/Set-CardDefaultTeamsSetting.ps1',
	           'Public/Application/Templates/DesignerFrameTemplate.html',
	           'Public/Application/Templates/EdgeAppLoader.html',
	           'Public/Application/Templates/HtmlTemplate.html',
	           'Public/Application/Templates/PreviewCard.html',
	           'Public/Application/Templates/PromptCard.html',
	           'Public/Application/Templates/Extension/Script/Badge.js',
	           'Public/Application/Templates/Extension/Script/Carousel.js',
	           'Public/Application/Templates/Extension/Script/Chart.Donut.js',
	           'Public/Application/Templates/Extension/Script/CodeBlock.js',
	           'Public/Application/Templates/Extension/Script/Layouts.js',
	           'Public/Application/Templates/Extension/Script/Media.js',
	           'Public/Application/Templates/Extension/Script/ProgressBar.js',
	           'Public/Application/Templates/Extension/Script/Rating.js',
	           'Public/Application/Templates/Extension/Style/Badge.Css',
	           'Public/Application/Templates/Extension/Style/Carousel.Css',
	           'Public/Application/Templates/Extension/Style/Chart.Donut.Css',
	           'Public/Application/Templates/Extension/Style/CodeBlock.Css',
	           'Public/Application/Templates/Extension/Style/Layouts.Css',
	           'Public/Application/Templates/Extension/Style/Media.Css',
	           'Public/Application/Templates/Extension/Style/ProgressBar.Css',
	           'Public/Application/Templates/Extension/Style/Rating.Css',
	           'Public/Charts/New-CardChartDonut.ps1',
	           'Public/Charts/New-CardChartGauge.ps1',
	           'Public/Containers/New-CardCarousel.ps1',
	           'Public/Containers/New-CardCarouselPage.ps1',
	           'Public/Containers/New-CardColumn.ps1',
	           'Public/Containers/New-CardColumnSet.ps1',
	           'Public/Containers/New-CardContainer.ps1',
	           'Public/Containers/New-CardFactSet.ps1',
	           'Public/Containers/New-CardImageSet.ps1',
	           'Public/Containers/New-CardTable.ps1',
	           'Public/Containers/Layout/New-CardGridArea.ps1',
	           'Public/Containers/Layout/New-CardLayoutAreaGrid.ps1',
	           'Public/Containers/Layout/New-CardLayoutFlow.ps1',
	           'Public/Containers/Layout/New-CardLayoutStack.ps1',
	           'Public/Elements/New-CardBadge.ps1',
	           'Public/Elements/New-CardCodeBlock.ps1',
	           'Public/Elements/New-CardCompoundButton.ps1',
	           'Public/Elements/New-CardIcon.ps1',
	           'Public/Elements/New-CardImage.ps1',
	           'Public/Elements/New-CardMedia.ps1',
	           'Public/Elements/New-CardProgressBar.ps1',
	           'Public/Elements/New-CardRichTextblock.ps1',
	           'Public/Elements/New-CardTextBlock.ps1',
	           'Public/Elements/Actions/New-CardActionOpenUrl.ps1',
	           'Public/Elements/Actions/New-CardActionSet.ps1',
	           'Public/Elements/Actions/New-CardActionShowCard.ps1',
	           'Public/Elements/Actions/New-CardActionSubmit.ps1',
	           'Public/Elements/Actions/New-CardActionToggleVisibility.ps1',
	           'Public/Elements/Sources/New-CardMediaCaptionSource.ps1',
	           'Public/Inputs/New-CardInputChoiceSet.ps1',
	           'Public/Inputs/New-CardInputDate.ps1',
	           'Public/Inputs/New-CardInputNumber.ps1',
	           'Public/Inputs/New-CardInputRating.ps1',
	           'Public/Inputs/New-CardInputText.ps1',
	           'Public/Inputs/New-CardInputTime.ps1',
	           'Public/Inputs/New-CardInputToggle.ps1',
	           'Public/Template/Build-CardFromTemplate.ps1',
	           'Public/Template/Find-CardTemplateTag.ps1',
	           'Public/Template/New-CardTemplateTag.ps1',
	           'schemas/AdaptiveCard.json'

# Private data to pass to the module specified in RootModule/ModuleToProcess. This may also contain a PSData hashtable with additional module metadata used by PowerShell.
PrivateData = @{

	PSData = @{

	    # Tags applied to this module. These help with module discovery in online galleries.
	    Tags = 'AdaptiveCards','Cards','PowerShell','MvRAdaptiveCards','MvR','MicrosoftTeams','Outlook','SMTP','Email','MsTeams','Teams'

	    # A URL to the license for this module.
	    LicenseUri = 'https://github.com/Michael19842/PowerShell.MvRAdaptiveCards.Module/blob/main/LICENSE'

	    # A URL to the main website for this project.
	    ProjectUri = 'https://github.com/Michael19842/PowerShell.MvRAdaptiveCards.Module'

	    # A URL to an icon representing this module.
	    IconUri = 'https://raw.githubusercontent.com/Michael19842/PowerShell.MvRAdaptiveCards.Module/main/docs/images/logo40x57.png'

	    # ReleaseNotes of this module
	    ReleaseNotes = '## Version 0.8.0 - 2025-01-15

### Added
- New chart functions: New-CardChartDonut with Chart.js integration
- ProgressBar element with determinate/indeterminate modes
- WebView2 support for Windows with auto-fallback to browser
- Template tag system for dynamic card generation
- 965+ comprehensive Pester tests

### Improved
- Enhanced EdgeApp mode with custom window sizing
- Better error handling across all functions
- Cross-platform compatibility (PS 5.1 and 7+)
- Performance optimizations in template processing

### Fixed
- WebView2 window closing in EdgeApp mode
- JSON serialization for special characters
- Template tag replacement with complex objects

### Breaking Changes
- None

See full changelog: https://github.com/Michael19842/PowerShell.MvRAdaptiveCards.Module/blob/main/CHANGELOG.md'

	    # Prerelease string of this module
	    # Prerelease = ''

	    # Flag to indicate whether the module requires explicit user acceptance for install/update/save
	    # RequireLicenseAcceptance = $false

	    # External dependent modules of this module
	    # ExternalModuleDependencies = @()

	} # End of PSData hashtable

 } # End of PrivateData hashtable

# HelpInfo URI of this module
HelpInfoURI = 'https://github.com/Michael19842/PowerShell.MvRAdaptiveCards.Module'

# Default prefix for commands exported from this module. Override the default prefix using Import-Module -Prefix.
# DefaultCommandPrefix = ''

}

